/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type problemDetails = {
    /**
     * URI reference to human-readable documentation for the problem type.
     */
    type: string;
    /**
     * Short, human-readable summary of the problem type.
     */
    title: string;
    /**
     * HTTP status code generated by the origin server.
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence of the problem.
     */
    detail: string;
    /**
     * URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * Validation errors, if any.
     */
    errors?: Record<string, Array<string>>;
};

